---
title: "Lecture7: A2,B2"
date: Sys.Date()
output: html_document
---

### Library
```{r libs}
library('data.table')
```

### Paths
```{r paths}
# path = "/Users/alevi/Downloads/"
# path = "\\Users\\shawn\\Desktop\\"
path = "~/Carmel/RProjects/Lab_Benjamini/data"
```

### Load data
```{r dat}
load(sprintf("%s/reads_100_A2.rda",path))
load(sprintf("%s/reads_100_B2.rda",path))
load(sprintf("%s/GC_100.rda",path))
```

```{r}
chr2t_mat = matrix(reads_100_A2, nr = 50)
# chr2t_mat[,1:2]
# reads_100_A2[1:2]
reads_5K_t = colSums(chr2t_mat)

chr2n_mat = matrix(reads_100_B2, nr = 50)
# chr2n_mat[,1:2]
# reads_100_B2[1:2]
reads_5K_n = colSums(chr2n_mat)

gc_mat = matrix(GC_100,nr=50)
GC_5K = colMeans(gc_mat)
```


### Run `manipulate` only in console
```{r interactive, eval= FALSE}
library('manipulate')
pl = 5000
manipulate(plot(x+(1:pl),reads_5K_t[x+(1:pl)],ylim = c(0,600),
                pch=20,cex =0.5), 
           x = slider(1, length(reads_5K_t)-pl+1,200))
```

```{r}
set.seed(50)
samp1 = sample(length(reads_5K_n),5000)

par(mfcol =c(2,1),mar =c(1,1,1,1))
plot(GC_5K[samp1],reads_5K_n[samp1],ylim = c(0,600),xlim = c(0,.75), cex = 0.4, pch=20)
abline(v=c(0.35,0.45))
plot(GC_5K[samp1],reads_5K_t[samp1],ylim = c(0,600),xlim = c(0,.75),cex = 0.4, pch=20)
abline(v=c(0.35,0.45))
par(mfcol =c(1,1))

```

## learn parameters from chromosome 1

```{r}
l_2n = length(reads_5K_n)
l_2t = length(reads_5K_t)

GC=GC_5K[1:l_2n]
mod_2n = lm(reads_5K_n~poly(GC, degree = 3),subset = reads_5K_n>50 & reads_5K_n<600 )

pred_range = seq(0.2,0.75,0.01)
resp_n = predict(mod_2n,list(GC=pred_range))
preds2n = predict(mod_2n,list(GC=GC_5K))

par(mfcol = c(1,1),mar = c(3,3,3,3))
plot(GC_5K[samp1],reads_5K_n[samp1],ylim = c(0,600),xlim = c(0.2,.75), cex = 0.5, pch=20, ylab = "Healthy")
lines(pred_range, resp_n,col = 4,lw=3)

```

```{r}
GC=GC_5K[1:l_2t]
mod_2t = lm(reads_5K_t~poly(GC, degree = 3),subset = (reads_5K_t>50)&(reads_5K_t<500))

pred_range = seq(0.2,0.75,0.01)
resp_t = predict(mod_2t,list(GC=pred_range))
preds2t = predict(mod_2t,list(GC=GC_5K))

par(mfcol = c(1,1),mar = c(3,5,3,3))
plot(GC_5K[samp1],reads_5K_t[samp1],ylim = c(0,600),xlim = c(0.2,.75), cex = 0.5, pch=20, ylab = "Tumor")
lines(pred_range, resp_t,col = 2,lw=3)
lines(pred_range, resp_n,col = 4,lw=3)
```

## One sample corrections
```{r}
one_sample_correct = function(samp, preds) {
  one_correct = (samp)/(preds)
  return(one_correct)
}
```

```{r }
corrected_1n = 
  one_sample_correct (reads_5K_n,preds2n[1:l_2n])
uncorrected_1n = (reads_5K_n)/median(reads_5K_n) 

corrected_1t = 
  one_sample_correct (reads_5K_t,preds2t[1:l_2t])
uncorrected_1t = (reads_5K_t)/median(reads_5K_t) 
```

```{r plot_spatial_range}
par(mfcol = c(2,1),mar = c(2,2,2,2))
range_a = 5000:6000
plot(corrected_2t[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20,main = "Tumor")
abline(h=1,col=4)
plot(uncorrected_2t[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20,)
abline(h=1,col=4)

par(mfcol = c(2,1),mar = c(2,2,2,2))
range_a = 5000:6000
plot(corrected_2n[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20)
abline(h=1,col=4)
plot(uncorrected_2n[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20)
abline(h=1,col=4)

```
