---
title: "Lecture7: A1,B1 (Edit V3)"
date: Sys.Date()
output:
  html_document:
    code_folding: show
editor_options: 
  markdown: 
    wrap: sentence
---

### Library
```{r libs}
# library('data.table')
```

### Paths
```{r paths}
# path = "/Users/alevi/Downloads/"
# path = "\\Users\\shawn\\Desktop\\"
path = "~/Carmel/RProjects/Lab_Benjamini/data"
```

### Load data
```{r dat}
load(sprintf("%s/reads_100_A1.rda",path))
load(sprintf("%s/reads_100_B1.rda",path))
load(sprintf("%s/GC_100.rda",path))
```

#Binning
```{r binning}
binsize = 25
chr1t_mat = matrix(reads_100_A1, nr = binsize)
# chr1t_mat[,1:2]
# reads_100_A1[1:2]
reads_2.5K_t1 = colSums(chr1t_mat)

chr1n_mat = matrix(reads_100_B1, nr = binsize)
# chr1n_mat[,1:2]
# reads_100_B1[1:2]
reads_2.5K_n1 = colSums(chr1n_mat)

gc_mat = matrix(GC_100,nr=binsize)
GC_2.5K = colMeans(gc_mat)
GC_2.5K=GC_2.5K[1: (length(reads_2.5K_n1)) ]
```


### Run `manipulate` only in console
```{r interactive, eval= FALSE}
## TUMOR
library('manipulate')
pl = 2500
manipulate(plot(x+(1:pl),reads_2.5K_t1[x+(1:pl)],ylim = c(0,600),
                pch=20,cex =0.5), 
           x = slider(1, length(reads_2.5K_t1)-pl+1,200))
```

```{r sampling_2.5K}
set.seed(50)
samp1 = sample(length(reads_2.5K_n1),5000)
```

```{r plot_adj}
# Plot adjacent

par(mfcol =c(2,1),mar =c(1,5,1,1))
plot(GC_2.5K[samp1],reads_2.5K_n1[samp1],ylim = c(0,600),xlim = c(0,.75), cex = 0.4, pch=20, ylab="Healthy 1")
abline(v=c(0.35,0.45))
plot(GC_2.5K[samp1],reads_2.5K_t1[samp1],ylim = c(0,600),xlim = c(0,.75),cex = 0.4, pch=20, ylab="Tumor 1")
abline(v=c(0.35,0.45))

par(mfcol =c(1,2),mar =c(1,1,1,1))
plot(GC_2.5K[samp1],reads_2.5K_n1[samp1],ylim = c(0,600),xlim = c(0,.75), cex = 0.4, pch=20, main="Healthy 1")
abline(h=c(180,400))
plot(GC_2.5K[samp1],reads_2.5K_t1[samp1],ylim = c(0,600),xlim = c(0,.75),cex = 0.4, pch=20, main="Tumor 1")
abline(h=c(180,400))

par(mfcol =c(1,1))

```

## Learn parameters from chromosome 1

```{r}
l_1n = length(reads_2.5K_n1)
l_1t = length(reads_2.5K_t1)

GC=GC_2.5K[1:l_1n]
mod_1n = lm(reads_2.5K_n1~poly(GC, degree = 3),subset = reads_2.5K_n1>50 & reads_2.5K_n1<600 )

pred_range = seq(0.2,0.75,0.01)
resp_n = predict(mod_1n,list(GC=pred_range))
preds1n = predict(mod_1n,list(GC=GC_2.5K))

par(mfcol = c(1,1),mar = c(3,5,3,3))
plot(GC_2.5K[samp1],reads_2.5K_n1[samp1],ylim = c(0,600),xlim = c(0.2,.75), cex = 0.5, pch=20, ylab = "Healthy 1")
lines(pred_range, resp_n,col = 4,lw=3)

```

```{r}
GC=GC_2.5K[1:l_1t]
mod_1t = lm(reads_2.5K_t1~poly(GC, degree = 3),subset = (reads_2.5K_t1>50)&(reads_2.5K_t1<500))

pred_range = seq(0.2,0.75,0.01)
resp_t = predict(mod_1t,list(GC=pred_range))
preds1t = predict(mod_1t,list(GC=GC_2.5K))

par(mfcol = c(1,1),mar = c(3,3,3,3))
plot(GC_2.5K[samp1],reads_2.5K_t1[samp1],ylim = c(0,600),xlim = c(0.2,.75), cex = 0.5, pch=20, main = "Tumor 1")
lines(pred_range, resp_t,col = 2,lw=3)
lines(pred_range, resp_n,col = 4,lw=3)
```

## One sample corrections
```{r func_fix}
one_sample_correct = function(samp, preds) {
  one_correct = (samp)/(preds)
  return(one_correct)
}
```

```{r fix}
corrected_1n = one_sample_correct(reads_2.5K_n1,preds1n[1:l_1n])
uncorrected_1n = (reads_2.5K_n1)/median(reads_2.5K_n1) 

corrected_1t = one_sample_correct(reads_2.5K_t1,preds1t[1:l_1t])
uncorrected_1t = (reads_2.5K_t1)/median(reads_2.5K_t1) 

range_a = 5000:6000
```

```{r plot_bef_af}
par(mfcol = c(2,1),mar = c(2,5,2,2))

plot(uncorrected_1n[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Before Fix", main = "Healthy 1")
abline(h=1,col=4)
plot(corrected_1n[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Corrected")
abline(h=1,col=4)

plot(uncorrected_1t[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Before Fix", main = "Tumor 1")
abline(h=1,col=4)
plot(corrected_1t[range_a], ylim = c(0,2.5),cex = 0.5, pch=20, ylab = "Corrected")
abline(h=1,col=4)

```

```{r plot_tn_befaf}
par(mfcol = c(2,1),mar = c(2,5,2,2))

plot(uncorrected_1n[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Healthy 1", main = "Before Fix")
abline(h=1,col=4)

plot(uncorrected_1t[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Tumor 1")
abline(h=1,col=4)

plot(corrected_1n[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Healthy 1", main = "Corrected")
abline(h=1,col=4)
plot(corrected_1t[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Tumor 1")
abline(h=1,col=4)

```


```{r plot_tn_stacked}
par(mfcol = c(4,1),mar = c(2,5,2,2))

plot(uncorrected_1n[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Healthy 1", main = "Before Fix")
abline(h=1,col=4)
plot(uncorrected_1t[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Tumor 1")
abline(h=1,col=4)

plot(corrected_1n[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Healthy 1", main = "Corrected")
abline(h=1,col=4)
plot(corrected_1t[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Tumor 1")
abline(h=1,col=4)

```


```{r}
cat("GC \n")
head(GC_100, 10)
head(round(GC_2.5K,2), 10)

cat("\n", "Healthy")
cat("\n", "Original")
head(reads_100_B1, 10)
summary(reads_100_B1)
cat(" Binned")
head(reads_2.5K_n1, 10)
summary(reads_2.5K_n1)


cat("\n", "Tumor")
cat("\n", "Original")
head(reads_100_A1, 10)
summary(reads_100_A1)
cat(" Binned")
head(reads_2.5K_t1, 10)
summary(reads_2.5K_t1)
```

```{r cor}
plot(reads_2.5K_n1[samp1],reads_2.5K_t1[samp1], xlim=c(0,600),ylim=c(0,600),cex=0.5,pch=20)
```
We'll normalize by dividing each by its corresponding median.
```{r cor_med_fix}

##
med_n1 = median(reads_2.5K_n1[samp1])
med_t1 = median(reads_2.5K_t1[samp1])
plot(reads_2.5K_n1[samp1]/med_n1,reads_2.5K_t1[samp1]/med_t1, xlim=c(0,3),ylim=c(0,3),cex=0.5,pch=20)
```

12:30 negative control (the healthy sample, that i don't expect there to have an effect when I don't expect a sharp) 
12:33 the regression is not entirely linear
12:34 If we disregard, GC

$$
{Y_k}^n \ \text{ Normative sample (Healthy)} \\
{Y_k}^t \sim  \ \text{ Tumor sample (Cancerous)} \\
\lambda_k \ \text{Mean Expected value of number of reads} \\
\mathcal{E}_K \\
\gamma^n \neq \gamma^t \ \text{ Poisson "noise"} \\
\eta^j \ \text{ Joint "noise"} \\
\text{Assumption: per location } k\in (0,len) \text{ the variances should be the same.} \\
\text{This means that we expect } \eta^n / \eta^t \approx 1

$$
After recess:

$$
\hat{a}_k^{(\#3)} \text{ This is a two-sample estimator that takes GC content into account}\\
\text{This means that we expect } \eta^n / \eta^t \approx 1 \\
\text{Problems with estimators that are a if the denominator is close to 0.} \\
\text{Currently, we will assume that } f_K(GC) \text{ is a constant.}\\
\text{Problems with estimators that are a if the denominator is close to 0.}\\
\\
\hat{a}_k^{(\#3)} = \frac{}{\frac{{Y_k}^n}{{\hat{f}_k}^n{GC}_k}+\mathcal{E}}
$$
