---
title: "Lecture7: A2,B2 (Edit V3)"
date: Sys.Date()
output:
  html_document:
    code_folding: show
editor_options: 
  markdown: 
    wrap: sentence
---

### Library
```{r libs}
library('data.table')
```

### Paths
```{r paths}
# path = "/Users/alevi/Downloads/"
# path = "\\Users\\shawn\\Desktop\\"
path = "~/Carmel/RProjects/Lab_Benjamini/data"
```

### Functions
```{r help_funcs}
source(file.path(path, "help_funcs.R"))
helpers = list(loadRData = loadRData, binReads = binReads)
```

### Load data
```{r dat}
load(sprintf("%s/reads_100_A2.rda",path)) #t(umor)
load(sprintf("%s/reads_100_B2.rda",path)) #n(ot)
load(sprintf("%s/GC_100.rda",path))
```



### Binning (5K)

```{r binning_5K}
chr2t_mat = matrix(reads_100_A2, nr = 50)
chr2t_mat[,1:2]
reads_100_A2[1:2]
reads_5K_t = colSums(chr2t_mat)

chr2n_mat = matrix(reads_100_B2, nr = 50)
chr2n_mat[,1:2]
reads_100_B2[1:2]
reads_5K_n = colSums(chr2n_mat)

gc_mat = matrix(GC_100,nr=50)
GC_5K = colMeans(gc_mat)
```


### Binning (2.5K)

```{r binning_2.5K}
binsize_hundreds = 25

chr2t_mat = matrix(reads_100_A2, nr = binsize_hundreds)
chr2t_mat[,1:2]
reads_100_A2[1:2]
reads_2.5K_t = colSums(chr2t_mat)

chr2n_mat = matrix(reads_100_B2, nr = binsize_hundreds)
chr2n_mat[,1:2]
reads_100_B2[1:2]
reads_2.5K_n = colSums(chr2n_mat)

gc_mat = matrix(GC_100, nr = binsize_hundreds)
GC_2.5K = colMeans(gc_mat)
```

### Binning (---)
```{r n_reads}
# binBases100s = function(vec_100,size_in_hundreds){
#   vec_100 = matrix(vec_100, nr = size_in_hundreds)
#   return(colSums(vec_100))
# }
# 
# binsize_hundreds = 50
# reads_5K_n = binBases100s(reads_100_B2, binsize_hundreds)
# reads_5K_t = binBases100s(reads_100_A2, binsize_hundreds)
# GC_5K = binBases100s(GC_100, binsize_hundreds)
# if(any(GC_5K>1)){GC_5K = GC_5K / binsize_hundreds} # convert GC_5K into percentages

```

### Removing outliers
```{r outliers}
#   # bins w/ at least 30% GC content
# cleanData = function(GC_vec,reads_A,reads_B){
#   
#   # outliers of gc percent per bin
#   zeros_GC = GC_vec == 0 #bins w/o GC content
#   small_GC = GC_vec <= 0.3 & GC_vec > 0 #low-GC content bins (<30%)
#   
#   # identify outliers of reads count per bin
#   zscore_A = (reads_A - mean(reads_A)) / sd(reads_A)
#   xtreme_reads_A = abs(zscore_A) > 2
#   
#   zscore_B = (reads_B - mean(reads_B)) / sd(reads_B)
#   xtreme_reads_B = abs(zscore_B) > 2
#   
#   # create new variables without outliers
#   outliers = (zeros_GC | small_GC | xtreme_reads_A | xtreme_reads_B)
#   GC_clean = GC_vec[!outliers]
#   reads_A_clean = reads_A[!outliers]
#   reads_B_clean = reads_B[!outliers]
# 
#   return(GC_clean, reads_A_clean, reads_B_clean)
# }

```

### Run `manipulate` only in console
```{r manipulate,eval= FALSE}
library('manipulate')
pl = 5000
manipulate(plot(x+(1:pl),reads_5K_t[x+(1:pl)],ylim = c(0,600),
                pch=20,cex =0.5),
           x = slider(1, length(reads_5K_t)-pl+1,200))
```


```{r plot_reads}
set.seed(50)
samp1 = sample(length(reads_5K_n),5000)

par(mfcol =c(2,2)) #limiting margins truncates labels
plot(GC_5K[samp1],reads_5K_n[samp1],ylim = c(0,600),xlim = c(0,.75), cex = 0.4, pch=20, 
     ylab="Healthy Reads", xlab="GC (%)", main = "Bins of 5K")
plot(GC_5K[samp1],reads_5K_t[samp1],ylim = c(0,600),xlim = c(0,.75),cex = 0.4, pch=20,  
     ylab="Tumor Reads",xlab="GC (%)")
plot(GC_2.5K[samp1],reads_2.5K_n[samp1],ylim = c(0,300),xlim = c(0,.75), cex = 0.4, pch=20, 
     ylab="Healthy Reads", xlab="GC (%)", main = "Bins of 2.5K")
plot(GC_2.5K[samp1],reads_2.5K_t[samp1],ylim = c(0,300),xlim = c(0,.75),cex = 0.4, pch=20,  
     ylab="Tumor Reads (2.5K)", xlab="GC (%)")
# par(mfcol =c(1,1))

# mar = c(bottom, left, top, right)
# margin size specified in inches.
# The default is c(5, 4, 4, 2) + 0.1.
```


# Learn parameters from chromosome 1

```{r}
len_5K_2n = length(reads_5K_n)
len_5K_2t = length(reads_5K_t)

par(mfcol = c(1,1),mar = c(3,3,3,3))
plot(GC_5K[samp1],reads_5K_n[samp1],ylim = c(0,600),xlim = c(0.2,.75), 
     cex = 0.5, pch=20, main = "Healthy (5K)")

GC = GC_5K[1:len_5K_2n]
mod_2n = lm(reads_5K_n~poly(GC, degree = 3),subset = reads_5K_n>50 & reads_5K_n<600 )

pred_range = seq(0.2,0.75,0.01)
resp_n = predict(mod_2n,list(GC=pred_range))
lines(pred_range, resp_n,col = 4,lw=3)

preds2n = predict(mod_2n,list(GC=GC_5K))

```





```{r}
par(mfcol = c(1,1))
plot(GC_5K[samp1],reads_5K_t[samp1],ylim = c(0,600),xlim = c(0.2,.75), 
     cex = 0.5, pch=20, main = "Tumor (5K)")

GC=GC_5K[1:len_5K_2t]
mod_2t = lm(reads_5K_t~poly(GC, degree = 3),subset = (reads_5K_t>50)&(reads_5K_t<500))

pred_range = seq(0.2, 0.75, 0.01)
resp_t = predict(mod_2t,list(GC=pred_range))
lines(pred_range, resp_t,col = 4,lw=3)
preds2t = predict(mod_2t,list(GC=GC_5K))

lines(pred_range, resp_n,col = 2,lw=3)

```

```{r}
par(mfcol = c(1,2))
plot(GC_5K[samp1],reads_5K_t[samp1],ylim = c(0,800),xlim = c(0.2,.75), 
     cex = 0.5, pch=20, main = "Tumor (5K)")
plot(GC_5K[samp1],reads_5K_n[samp1],ylim = c(0,800),xlim = c(0.2,.75), 
     cex = 0.5, pch=20, main = "Healthy (5K)")
# par(mfcol = c(1,1))
```




### One sample corrections

```{r}
one_sample_correct = function(samp, preds) {
  one_correct = (samp)/(preds)
  return(one_correct)
}

```



```{r}
corrected_2n = 
  one_sample_correct (reads_5K_n,preds2n[1:len_5K_2n])
uncorrected_2n = (reads_5K_n)/median(reads_5K_n) 

corrected_2t = 
  one_sample_correct (reads_5K_t,preds2t[1:len_5K_2t])
uncorrected_2t = (reads_5K_t)/median(reads_5K_t) 
```





```{r}
par(mfcol = c(2,1),mar = c(2,2,2,2))
range_a = 5000:6000
plot(corrected_2t[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20,main = "Tumor Corrected")
abline(h=1,col=4,lw=1.5)
plot(uncorrected_2t[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20,main = "Tumor Uncorrected")
abline(h=1,col=4,lw=1.5)

```





```{r}
par(mfcol = c(2,1),mar = c(2,2,2,2))
range_a = 5000:6000
plot(corrected_2n[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20, main = "Healthy Corrected")
abline(h=1,col=4,lw=1.5)
plot(uncorrected_2n[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20, main = "Healthy Uncorrected")
abline(h=1,col=4,lw=1.5)

```



```{r}
par(mfcol = c(2,2),mar = c(2,2,2,2))
range_a = 5000:6000

plot(corrected_2t[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20,main = "Tumor Corrected")
abline(h=1,col=4,lw=1.5)
plot(uncorrected_2t[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20,main = "Tumor Uncorrected")
abline(h=1,col=4,lw=1.5)


plot(corrected_2n[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20, main = "Healthy Corrected")
abline(h=1,col=4,lw=1.5)
plot(uncorrected_2n[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20, main = "Healthy Uncorrected")
abline(h=1,col=4,lw=1.5)

par(mfcol = c(1,1),mar = c(2,2,2,2))
```

