---
title: "Lab Task 6"
author: "Group 6"
date: Sys.Date()
output:
  html_document:
    code_folding: show
editor_options: 
  markdown: 
    wrap: sentence
---

Group members:

- Shawn Yakir , 315714980,  shawn.yakir@mail.huji.ac.il
- Sarah Levitz, 324673623, sarah.levitz@mail.huji.ac.il
- Carmel Baris, 318455276, carmel.baris@mail.huji.ac.il 

### Clean the environment
```{r clean}
rm(list = ls())
```

### Libraries used

```{r libraries}
library('splines')
```


### Paths
```{r paths}
path = "C:/Users/user/Documents/Carmel/Projects/HUJI/Archive_HUJI/data-analysis-genomics/data"
# path = "/Users/alevi/Downloads/"
# path = "\\Users\\shawn\\Desktop\\"
```


### Helper functions
```{r helpers}
helpers_file = file.path(path, "help_funcs.R")
source(helpers_file)
helpers = list(loadRData = loadRData, binReads = binReads)
```


### Load data
```{r dat}
load(sprintf("%s/reads_100_A2.rda",path))
load(sprintf("%s/reads_100_B2.rda",path))
load(sprintf("%s/GC_100.rda",path))
GC_100=GC_100[1: (length(reads_100_A2)) ]
```

### Binning
```{r binning}
binsize = 25
chr1t_mat = matrix(reads_100_A2, nr = binsize)
# chr1t_mat[,1:2]
# reads_100_A2[1:2]
reads2.5K_t2 = colSums(chr1t_mat)

chr1n_mat = matrix(reads_100_B2, nr = binsize)
# chr1n_mat[,1:2]
# reads_100_B2[1:2]
reads2.5K_n2 = colSums(chr1n_mat)

gc_mat = matrix(GC_100,nr=binsize)
GC2.5K = colMeans(gc_mat)
```






### Outliers
```{r outliers}
# outliers of gc percent per bin
zeros_GC = GC2.5K == 0 #bins w/o GC content
small_GC = GC2.5K <= 0.3 & GC2.5K > 0 #low-GC content bins (<30%)
# valid_GC = !(zeros_GC | small_GC) #bins w/ at least 30% GC content

# identify outliers of reads count per bin
z_scores_n2 = (reads2.5K_n2 - mean(reads2.5K_n2)) / sd(reads2.5K_n2)
z_scores_t2 = (reads2.5K_t2 - mean(reads2.5K_t2)) / sd(reads2.5K_t2)
xtreme_reads_n2 = abs(z_scores_n2) > 3
xtreme_reads_t2 = abs(z_scores_t2) > 3

# create new variables without outliers
outliers = (zeros_GC | xtreme_reads_t2 | xtreme_reads_n2)
outliers = (outliers | (reads2.5K_t2<0.05) | (reads2.5K_n2<0.05))
reads2.5K_n2_clean = reads2.5K_n2[!outliers]
reads2.5K_t2_clean = reads2.5K_t2[!outliers]
GC2.5K_clean = GC2.5K[!outliers]
```

### Fitting bspline regression
```{r fit}
f = function(X, Y, degree=3, knots=c(0.415, 0.45, 0.54), sub_filter=NA) {
  lm(Y ~ bs(X, degree = degree, knots = knots, Boundary.knots = c(min(X), max(X))), subset = sub_filter)
}

```



```{r normalizing}
# Install and load the scales package if you haven't already
# install.packages("scales")
library(scales)

# Use the rescale function from the scales package
reads2.5K_n2_normalized <- rescale(reads2.5K_n2_clean, to = c(0, 100000))
reads2.5K_t2_normalized <- rescale(reads2.5K_t2_clean, to = c(0, 100000))

# Plot the normalized data
set.seed(50)
samp1 = sample(length(reads2.5K_n2), 5000)
```

```{r}
# Plot adjacent
par(mfcol = c(2, 1), mar = c(1, 5, 1, 1))
plot(GC2.5K_clean, reads2.5K_n2_normalized, cex = 0.4, pch = 20, ylab = "Healthy 2", ylim = c(1500, 40000), xlim = c(0.2, 0.75))
abline(v = c(0.35, 0.45))
plot(GC2.5K_clean, reads2.5K_t2_normalized, cex = 0.4, pch = 20, ylab = "Tumor 2", ylim = c(1500, 40000), xlim = c(0.2, 0.75))
abline(v = c(0.35, 0.45))

# Plot side by side
par(mfcol = c(1, 2), mar = c(1, 1, 1, 1))
par(mfcol = c(1, 2))
plot(GC2.5K_clean, reads2.5K_n2_normalized, cex = 0.4, pch = 20, main = "Healthy 2", ylim = c(5000, 40000), xlim = c(0.2, 0.75))
abline(h = c(0.3, 0.7))
plot(GC2.5K_clean, reads2.5K_t2_normalized, cex = 0.4, pch = 20, main = "Tumor 2", ylim = c(5000, 40000), xlim = c(0.2, 0.75))
abline(h = c(0.3, 0.7))


```


```{r scaling}
# Standardize the data using scale function
reads2.5K_n2_std <- scale(reads2.5K_n2)
reads2.5K_t2_std <- scale(reads2.5K_t2)

# Plot the standardized data
set.seed(50)
samp1 = sample(length(reads2.5K_n2), 5000)

# Plot adjacent
par(mfcol = c(2, 1), mar = c(1, 5, 1, 1))
plot(GC2.5K[samp1], reads2.5K_n2_std[samp1], ylim = c(-0.5, 0.5), xlim = c(0, 0.75), cex = 0.4, pch = 20, ylab = "Healthy 2")
abline(v = c(0.35, 0.45))
plot(GC2.5K[samp1], reads2.5K_t2_std[samp1], ylim = c(-0.5, 0.5), xlim = c(0, 0.75), cex = 0.4, pch = 20, ylab = "Tumor 2")
abline(v = c(0.35, 0.45))

# Plot side by side
par(mfcol = c(1, 2), mar = c(1, 1, 1, 1))
plot(GC2.5K[samp1], reads2.5K_n2_std[samp1], ylim = c(-0.5, 0.5), xlim = c(0, 0.75), cex = 0.4, pch = 20, main = "Healthy 2")
abline(h = c(-2, 2))
plot(GC2.5K[samp1], reads2.5K_t2_std[samp1], ylim = c(-0.5, 0.5), xlim = c(0, 0.75), cex = 0.4, pch = 20, main = "Tumor 2")
abline(h = c(-2, 2))

```

```{r sampling_2.5K}
set.seed(50)
samp1 = sample(length(reads2.5K_n2),5000)
```

```{r plot_adj}
# Plot adjacent

par(mfcol =c(2,1),mar =c(1,5,1,1))
plot(GC2.5K[samp1],reads2.5K_n2_std[samp1],ylim = c(0,600),xlim = c(0,.75), cex = 0.4, pch=20, ylab="Healthy 2")
abline(v=c(0.35,0.45))
plot(GC2.5K[samp1],reads2.5K_t2_std[samp1],ylim = c(0,600),xlim = c(0,.75),cex = 0.4, pch=20, ylab="Tumor 2")
abline(v=c(0.35,0.45))

par(mfcol =c(1,2),mar =c(1,1,1,1))
plot(GC2.5K[samp1],reads2.5K_n2_std[samp1],ylim = c(0,600),xlim = c(0,.75), cex = 0.4, pch=20, main="Healthy 2")
abline(h=c(180,400))
plot(GC2.5K[samp1],reads2.5K_t2_std[samp1],ylim = c(0,600),xlim = c(0,.75),cex = 0.4, pch=20, main="Tumor 2")
abline(h=c(180,400))

par(mfcol =c(1,1))

```


