---
title: "My Markdown Templates"
author: "Carmel Baris"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## Styled Table (Striped)

```{r point_estimators, echo=FALSE, results='asis', warning=FALSE}
striped <- data.frame (first_column  = c("value_1", "value_2"),
                  second_column = c("value_3", "value_4")
                  )


library(kableExtra)
striped %>%
  kbl(digits=2, row.names=FALSE,
      format.args = list(big.mark = '')) %>%
  kable_styling(bootstrap_options = c("striped", "hover"),
                fixed_thead = TRUE,
                font_size = 10) %>%
  scroll_box(NULL)


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


## Styled Simple Table

```{r}
simple <- data.frame (first_column  = c("value_1", "value_2"),
                  second_column = c("value_3", "value_4")
                  )


library(kableExtra)
simple %>%
  kbl(digits=2, row.names=FALSE, 
      col.names = c("column_1", "column_2"),
      format.args = list(big.mark = '')) %>%
    kable_classic(full_width = F, html_font = "Cambria")

```



\newpage

## Resources
1. [Creating styled tables](https://haozhu233.github.io/kableExtra/awesome_table_in_html.html)
2. [Cleaning the .RData file](https://thatdarndata.com/how-to-delete-your-saved-workspace-in-r/)