---
title: "Task1_Group6"
date: "May 2024"
output:
  html_document:
    code_folding: hide
editor_options: 
  markdown: 
    wrap: sentence
---

## A. Load & Prep Data

```{r}
######## LOAD DATA

## step 0: download rda file from moodle 
## group A gets bases 10M to 30M from chromosome1

## step 1: update directory, do NOT end with slash '/'
dir_name = "C:/Users/user/Documents/Carmel/Projects/HUJI/Archive_HUJI/data-analysis-genomics/data"
# setwd(dir_name) #set current directory to path of RDA file
# print(getwd()) #verify change of directory

## step 2: concatenate full path of RDA file
chr1_str_path = sprintf("%s/%s", dir_name, "chr1_str_10M_30M.rda") 

## step 3: load str object to env
load(file = chr1_str_path) #large file so be patient
```

```{r}

######## PRE-PROCESS DATA

## step 4: split 'chr1_str_10M_30M' to a vector of  individual characters
##  step 4: factor() changes each label into a number ("A" becomes 1, etc).
chr1_single = unlist(strsplit(chr1_str_10M_30M, split = "")) #total of 20M+1 bases
n_20 = length(chr1_single) - 1
chr1_single_20M = chr1_single[0:n_20] #reduced to an even total of 20M bases exactly
chr1_vector = factor(chr1_single, c("A","T","C","G")) #each letter is assigned a number

```


## B. Count Occurrences of Every Nucleobase

```{r updated_func}
subSnippet <- function(start_indx=1, cell_size=1000){
  #' Retrieves a subsection of Chromosome 1 from reference genome.
  #' Calculates number of occurrences for each molecular base (A, T, C, G). 
  #' Nucleobases that their decoding is not certain appear in lowercase.
  #' Unknown nucleobases appear as N.
  #'
  #' @param start_indx location of first base in region of interest
  #' @param cell_size number of nucleobases included in analysis region

  beg_region = start_indx
  end_region = beg_region + cell_size - 1
#  chr1_list = unlist(strsplit(chr1_str_10M_30M, split = ""))
  chr1_snippet = chr1_vector[beg_region:end_region]
  return(list(occurrences_table = table(chr1_snippet),
              chr1_snippet = chr1_snippet))
}
```

Note: Default starting index (1) and cell size (1K nucleobases) can be overriden.

```{r sanity_subsnippet_func, echo=FALSE}
# result_sub = subSnippet(start_indx=20000001-10, cell_size=10)
# result_sub = subSnippet(cell_size=20000001)
result_sub = subSnippet()
counts = result_sub$occurrences_table
chr1_single = result_sub$chr1_single
chr1_snippet = result_sub$chr1_snippet
head(chr1_snippet, 100)
# print(list(chr1_single[1:10], length(chr1_single)))
# print(list(chr1_vector[1:10], length(chr1_vector)))
cat("\n", "Total nucleobases in scope:", sum(counts), "\n\n") #like cell size
print(counts)
```



