---
title: "Quiz 6"
author: "Carmel Baris"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The salary of married women has a LogNorm(8.6,1) distribution and the salary of married men is independent with a LogNorm(9,1) distribution.

The family income is the sum of the man's and woman's wages. 
Calculate the probability that the family income is less than 20,000

Use R to simulate at least 100,000 iterations.

Answer to a precision of three digits after the period


```{r house_estimator, echo=TRUE}

w.samples = 100000 #increase to increase precision (the more, the merrier)
m.samples = w.samples #total of 200,000 people sampled

women <- rlnorm(w.samples, 8.6, 1)
men <- rlnorm(m.samples, 9.0, 1)

#note that both variables are vectors, e.g is.vector(women)>>TRUE
estimator <- women + men #sum of vectors is also a vector
prob.under.20k <- sum(estimator < 20000) / length(estimator)
answer <- round(prob.under.20k, 4)
answer
```

