---
title: "Lecture7_new_Original"
author: "Yuval Benjamini"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Paths
```{r}
dir_name = "~/Carmel/RProjects/Lab_Benjamini/data"
# dir_name = "/Users/alevi/Downloads/"
# dir_name = "\\Users\\shawn\\Desktop\\"
```

Library
```{r}
library('data.table')
```
Functions
```{r}
helpers_file = file.path(dir_name, "help_funcs.R")
source(helpers_file)
helpers = list(loadRData = loadRData, binReads = binReads)
```

Read the file

```{r}
load(sprintf("%s/reads_100_A2.rda",dir_name)) #t(umor)
load(sprintf("%s/reads_100_B2.rda",dir_name)) #n(ot)
load(sprintf("%s/GC_100.rda",dir_name))
```

```{r t_reads}
#nr==nrow==limit_num_of_rows
chr1t_mat = matrix(reads_100_A2, nr = 50) # limit row number to 50
dim(chr1t_mat)
chr1t_mat[,1:10] # first 10 columns
reads_100_A2[1:2] # first two elements from cancerous sample
reads_5K_t = colSums(chr1t_mat) 
```

```{r n_reads}
chr1n_mat = matrix(reads_100_B2, nr = 50)
dim(chr1n_mat)
chr1n_mat[,1:2] # first two columns
reads_100_B2[1:2] # first two elements in healthy sample
reads_5K_n = colSums(chr1n_mat)
```


```{r gc}
gc_mat = matrix(GC_100,nr=50)
GC_5K = colMeans(gc_mat)
```

# Run manipulate in console
```{r}
# library('manipulate')
# pl = 5000
# manipulate(plot(x+(1:pl),reads_5K_t[x+(1:pl)],ylim = c(0,600),
#                 pch=20,cex =0.5), 
#            x = slider(1, length(reads_5K_t)-pl+1,200))
```



```{r scatter}
set.seed(50)
samp1 = sample(length(reads_5K_n),5000)

# mar = c(bottom, left, top, right)
# margin size specified in inches.
# The default is c(5, 4, 4, 2) + 0.1.
gc_q = unname(quantile(gc_mat, probs = c(0.25,0.5, 0.75)))

par(mfcol =c(2,1),mar =c(1,3,1,1)) #limiting margins truncates labels
plot(GC_5K[samp1],reads_5K_n[samp1],ylim = c(0,600),xlim = c(0,.75), cex = 0.4, pch=20, ylab="Healthy Reads", xlab="GC (%)")
abline(v=gc_q, col="forestgreen")
abline(h=median(reads_100_A2), col="tan2")
plot(GC_5K[samp1],reads_5K_t[samp1],ylim = c(0,600),xlim = c(0,.75),cex = 0.4, pch=20,  ylab="Tumor Reads")
abline(v=gc_q, col="forestgreen")
par(mfcol =c(1,1))

```


# learn parameters from chromosome 1

```{r}
l_1n = length(reads_5K_n)
l_1t = length(reads_5K_t)

par(mfcol = c(1,1),mar = c(3,3,3,3))
plot(GC_5K[samp1],reads_5K_n[samp1],ylim = c(0,600),xlim = c(0.2,.75), cex = 0.5, pch=20)

GC=GC_5K[1:l_1n]
mod_1n = lm(reads_5K_n~poly(GC, degree = 3),subset = reads_5K_n>50 & reads_5K_n<600 )

pred_range = seq(0.2,0.75,0.01)
resp_n = predict(mod_1n,list(GC=pred_range))
lines(pred_range, resp_n,col = 4,lw=3)

```





```{r}
preds1n = predict(mod_1n,list(GC=GC_5K))

```





```{r}
par(mfcol = c(1,1))
plot(GC_5K[samp1],reads_5K_t[samp1],ylim = c(0,600),xlim = c(0.2,.75), cex = 0.5, pch=20)

GC=GC_5K[1:l_1t]
mod_1t = lm(reads_5K_t~poly(GC, degree = 3),subset = (reads_5K_t>50)&(reads_5K_t<500))

pred_range = seq(0.2,0.75,0.01)
resp_t = predict(mod_1t,list(GC=pred_range))
lines(pred_range, resp_t,col = 4,lw=3)
preds1t = predict(mod_1t,list(GC=GC_5K))

lines(pred_range, resp_n,col = 2,lw=3)

```



# One sample corrections

```{r}
one_sample_correct = function(samp, preds) {
  one_correct = (samp)/(preds)
  return(one_correct)
}

```



```{r}
corrected_1n = 
  one_sample_correct (reads_5K_n,preds1n[1:l_1n])
uncorrected_1n = (reads_5K_n)/median(reads_5K_n) 

corrected_1t = 
  one_sample_correct (reads_5K_t,preds1t[1:l_1t])
uncorrected_1t = (reads_5K_t)/median(reads_5K_t) 
```





```{r}
par(mfcol = c(2,1),mar = c(2,2,2,2))
range_a = 5000:6000
plot(corrected_1t[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20,main = "Tumor")
abline(h=1,col=4)
plot(uncorrected_1t[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20,)
abline(h=1,col=4)

```





```{r}
par(mfcol = c(2,1),mar = c(2,2,2,2))
range_a = 5000:6000
plot(corrected_1n[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20)
abline(h=1,col=4)
plot(uncorrected_1n[range_a],
     ylim = c(0,2.5),cex = 0.5,pch=20)
abline(h=1,col=4)

```







```{r}


```





