---
title: "Lab Task 6"
author: "Group 6"
date: Sys.Date()
output:
  html_document:
    code_folding: show
editor_options: 
  markdown: 
    wrap: sentence
---

Group members:

- Shawn Yakir , 315714980,  shawn.yakir@mail.huji.ac.il
- Sarah Levitz, 324673623, sarah.levitz@mail.huji.ac.il
- Carmel Baris, 318455276, carmel.baris@mail.huji.ac.il 

### Clean the environment
```{r clean}
rm(list = ls())
```

### Libraries used

```{r libraries}
library('splines')
```


### Paths
```{r paths}
path = "~/Carmel/RProjects/Lab_Benjamini/data"
# path = "/Users/alevi/Downloads/"
# path = "\\Users\\shawn\\Desktop\\"
```


### Helper functions
```{r helpers}
helpers_file = file.path(path, "help_funcs.R")
source(helpers_file)
helpers = list(loadRData = loadRData, binReads = binReads)
```


### Load data
```{r dat}
load(sprintf("%s/reads_100_A2.rda",path))
load(sprintf("%s/reads_100_B2.rda",path))
load(sprintf("%s/GC_100.rda",path))
GC_100=GC_100[1: (length(reads_100_A2)) ]
```

### Binning
```{r binning}
binsize = 25
chr1t_mat = matrix(reads_100_A2, nr = binsize)
# chr1t_mat[,1:2]
# reads_100_A2[1:2]
reads2.5K_t2 = colSums(chr1t_mat)

chr1n_mat = matrix(reads_100_B2, nr = binsize)
# chr1n_mat[,1:2]
# reads_100_B2[1:2]
reads2.5K_n2 = colSums(chr1n_mat)

gc_mat = matrix(GC_100,nr=binsize)
GC2.5K = colMeans(gc_mat)
```






### Outliers
```{r outliers}
# outliers of gc percent per bin
zeros_GC = GC2.5K == 0 #bins w/o GC content
# small_GC = GC2.5K <= 0.3 & GC2.5K > 0 #low-GC content bins (<30%)
# valid_GC = !(zeros_GC | small_GC) #bins w/ at least 30% GC content

# identify outliers of reads count per bin
z_scores_n2 = (reads2.5K_n2 - mean(reads2.5K_n2)) / sd(reads2.5K_n2)
z_scores_t2 = (reads2.5K_t2 - mean(reads2.5K_t2)) / sd(reads2.5K_t2)
xtreme_reads_n2 = abs(z_scores_n2) > 3
xtreme_reads_t2 = abs(z_scores_t2) > 3

# create new variables without outliers
outliers = (zeros_GC | xtreme_reads_t2 | xtreme_reads_n2)
outliers = (outliers | (reads2.5K_t2<0.05) | (reads2.5K_n2<0.05))
reads2.5K_n2_clean = reads2.5K_n2[!outliers]
reads2.5K_t2_clean = reads2.5K_t2[!outliers]
GC2.5K_clean = GC2.5K[!outliers]
```

### Fitting bspline regression
```{r fit}
create_est_f = function(X, Y, degree, knots) {
  lknot <- min(X)
  rknot <- max(X)
  lm(Y ~ bs(X, degree = degree, knots = knots, Boundary.knots = c(lknot, rknot)))
}

```



```{r normalizing}
# Install and load the scales package if you haven't already
# install.packages("scales")
library(scales)

# Use the rescale function from the scales package
reads2.5K_n2_normalized <- rescale(reads2.5K_n2_clean, to = c(0, 100))
reads2.5K_t2_normalized <- rescale(reads2.5K_t2_clean, to = c(0, 100))
```

```{r}
# Plot the normalized data
set.seed(50)
samp1 = sample(length(reads2.5K_n2), 5000)
```

```{r}
# Plot adjacent
par(mfcol = c(2, 1), mar = c(1, 5, 1, 1))
plot(GC2.5K_clean[samp1], reads2.5K_n2_normalized[samp1], cex = 0.4, pch = 20, ylab = "Healthy 1", ylim = c(1.5, 35), xlim = c(0.2, 0.75))
plot(GC2.5K_clean[samp1], reads2.5K_t2_normalized[samp1], cex = 0.4, pch = 20, ylab = "Tumor 1", ylim = c(0, 35), xlim = c(0.2, 0.75))

# Plot side by side
par(mfcol = c(1, 2), mar = c(1, 1, 1, 1))
par(mfcol = c(1, 2))
plot(GC2.5K_clean[samp1], reads2.5K_n2_normalized[samp1], cex = 0.4, pch = 20, main = "Healthy 1", ylim = c(0, 35), xlim = c(0.2, 0.75))
plot(GC2.5K_clean[samp1], reads2.5K_t2_normalized[samp1], cex = 0.4, pch = 20, main = "Tumor 1", ylim = c(0, 35), xlim = c(0.2, 0.75))


```


## Learn parameters from chromosome 1

```{r}
l_1n = length(reads2.5K_n2_normalized)
l_1t = length(reads2.5K_t2_normalized)

GC=GC2.5K_clean[1:l_1n]
mod_1n = lm(reads2.5K_n2_normalized~poly(GC, degree = 3),subset = reads2.5K_n2_normalized>1.5 & reads2.5K_n2_normalized<35 )

pred_range = seq(0.2,0.75,0.01)
resp_n = predict(mod_1n,list(GC=pred_range))
preds1n = predict(mod_1n,list(GC=GC2.5K_clean))

par(mfcol = c(1,1),mar = c(3,5,3,3))
plot(GC2.5K_clean[samp1],reads2.5K_n2_normalized[samp1],ylim = c(0,35),xlim = c(0.2,.75), cex = 0.5, pch=20, ylab = "Healthy 1")
lines(pred_range, resp_n,col = 4,lw=3)

```


```{r}
GC=GC2.5K_clean[1:l_1t]
mod_1t = lm(reads2.5K_t2_normalized~poly(GC, degree = 3),subset = (reads2.5K_t2_normalized>1.5)&(reads2.5K_t2_normalized<40))

pred_range = seq(0.2,0.75,0.01)
resp_t = predict(mod_1t,list(GC=pred_range))
preds1t = predict(mod_1t,list(GC=GC2.5K_clean))

par(mfcol = c(1,1),mar = c(3,3,3,3))
plot(GC2.5K_clean[samp1],reads2.5K_t2_normalized[samp1],ylim = c(0,35),xlim = c(0.2,.75), cex = 0.5, pch=20, main = "Tumor 1")
lines(pred_range, resp_t,col = 2,lw=3)
lines(pred_range, resp_n,col = 4,lw=3)
```


## One sample corrections
```{r func_fix}
one_sample_correct = function(samp, preds) {
  one_correct = (samp)/(preds)
  return(one_correct)
}
```

```{r med_fix}
corrected_1n = one_sample_correct (reads2.5K_n2_normalized,preds1n[1:l_1n])
uncorrected_1n = (reads2.5K_n2_normalized)/median(reads2.5K_n2_normalized) 

corrected_1t = one_sample_correct (reads2.5K_t2_normalized,preds1t[1:l_1t])
uncorrected_1t = (reads2.5K_t2_normalized)/median(reads2.5K_t2_normalized) 

range_a = 5000:6000
```

```{r plot_bef_af}
par(mfcol = c(2,1),mar = c(2,5,2,2))

plot(uncorrected_1n[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Before Fix", main = "Healthy 1")
abline(h=1,col=4)
plot(corrected_1n[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Corrected")
abline(h=1,col=4)

plot(uncorrected_1t[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Before Fix", main = "Tumor 1")
abline(h=1,col=4)
plot(corrected_1t[range_a], ylim = c(0,2.5),cex = 0.5, pch=20, ylab = "Corrected")
abline(h=1,col=4)

```

```{r plot_tn_befaf}
par(mfcol = c(2,1),mar = c(2,5,2,2))

plot(uncorrected_1n[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Healthy 1", main = "Before Fix")
abline(h=1,col=4)

plot(uncorrected_1t[range_a], ylim = c(0,2.5),cex = 0.5,pch=20, ylab = "Tumor 1")
abline(h=1,col=4)

plot(corrected_1n[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Healthy 1", main = "Corrected")
abline(h=1,col=4)
plot(corrected_1t[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Tumor 1")
abline(h=1,col=4)

```


```{r plot_tn_stacked}
par(mfcol = c(4,1),mar = c(2,5,2,2))

plot(uncorrected_1n[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Healthy 1", main = "Before Fix")
abline(h=1,col=4)
plot(uncorrected_1t[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Tumor 1")
abline(h=1,col=4)

plot(corrected_1n[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Healthy 1", main = "Corrected")
abline(h=1,col=4)
plot(corrected_1t[range_a], ylim = c(0,2.5), cex = 0.5, pch=20, ylab = "Tumor 1")
abline(h=1,col=4)

```

### Introduction 

This week we...

### Q1: 

