---
title: "We Got The Beat"
author: "Sigal Falk & Carmel Baris"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background
The Swedish company, "Spotify", is an audio streaming and media services provider. Its digital services include a public REST-API which reveals the company's records of artists, albums, playlists, and songs. Specifically, the *"Track's Audio Features"*  endpoint provides quantitative attributes for each requested song. We selected a dataset based on this endpoint, which includes over 170K songs dated from 1921 till 2020. In our analysis we focused solely on the years 2017-2018 and on two key characteristics:
A. **Tempo**, also known as "metronome speed", which describes the estimated speed or pace of a given audio track. Measured in the number of Beats Per Minute (BPM).
B. **Danceability** index, which is a Spotifiy-origin describes the suitability of the song track for dancing and is based on the combination of several musical elements including rhythm, rhythm stability, the intensity of the music beats, and the general regularity of the audio track. Ranging from 0.0, an audio track that is not suitable for dancing, to 1.0, an audio track that is very suitable for dancing.
