---
title: "Task2"
date: Sys.Date()
output:
  html_document:
    code_folding: show
  pdf_document: default
editor_options:
  markdown:
    wrap: sentence
---

Team 6:
 - Shawn Yakir , 315714980, shawnyakir@gmail.com  
 - Sarah Levitz, 324673623, sarah.levitz@mail.huji.ac.il
 - Carmel Baris, 318455276, carmel.baris@mail.huji.ac.il


### Libraries used

```{r libraries, message=FALSE, warning=FALSE, include=FALSE}
library('ggplot2') # fread
library('data.table') # Part A_Q1
```


### Paths and Data


```{r data_A, message=FALSE, warning=FALSE, include=FALSE}

#helper functions
source("help_funcs.R")

# Load the data (Group A)
bases_file = "~/Carmel/RProjects/Lab_Benjamini/data/chr1_str_10M_30M.rda"
reads_file = '~/Carmel/RProjects/Lab_Benjamini/data/TCGA-13-0723-01A_lib2_all_chr1.forward'
# reads_file = "/Users/alevi/Downloads/ATCGA-13-0723-01A_lib2_all_chr1.forward/TCGA-13-0723-01A_lib2_all_chr1.forward"

# bases = getReadLine(bases_file, warn = FALSE)[1]
chr1_reads = fread(reads_file) 
colnames(chr1_reads) = c("Chrom","Loc","FragLen")

bases = load(file = bases_file)

```


```{r}

# Define region and cell size
beg_region = 1
end_region = 1+2e07
region_size = 50000000
cell_size = 5000
start_location = 10000000
num_cells <- region_size / cell_size

# Ensure the length of the bases matches the region size
bases = substring(bases, 1, region_size)

# Get read line of actual data
locations = chr1_reads$Loc
reads_20K = getReadLine(locations, beg_region, end_region)
Nsingle = length(reads_20K)
Ssingle = sum(reads_20K)


cg_counts = countCGInCell(bases, cell_size)


# Filter chr1_reads for the specified region
chr1_reads_region <- chr1_reads[Loc >= start_location & Loc < start_location + region_size]

# Count number of reads (that start a fragment) per bin
reads_per_bin <- countFragmentsPerBin(chr1_reads_region$Loc, cell_size, num_cells, start_location)

# Check correlation between CG counts and coverage
correlation = cor(cg_counts, reads_per_bin)

# Print the correlation
cat("Correlation between CG counts and read coverage:", correlation, "\n")

# Create a data frame for plotting
num_cells = region_size/cell_size
plot_data = data.frame(
  Cell = 1:num_cells,
  CG_Counts = cg_counts,
  Reads_Per_Bin = reads_per_bin
)

# Plot CG counts against the number of reads
ggplot(plot_data, aes(x = CG_Counts, y = Reads_Per_Bin)) +
  geom_point() +
  geom_smooth(method = "lm", col = "blue") +
  labs(title = "CG Counts vs Reads Per Bin",
       x = "Number of CG Bases",
       y = "Number of Reads") +
  theme_minimal()

# Display the plot
print(ggplot(plot_data, aes(x = CG_Counts, y = Reads_Per_Bin)) +
  geom_point() +
  geom_smooth(method = "lm", col = "blue") +
  labs(title = "CG Counts vs Reads Per Bin",
       x = "Number of CG Bases",
       y = "Number of Reads") +
  theme_minimal())



```
