---
title: "Lab Task 8"
author: "Group 6"
date: "`r format(Sys.time(), '%d/%m/%y')`"
output:
  html_document:
    code_folding: show
editor_options: 
  markdown: 
    wrap: sentence
---

Group members:

- Shawn Yakir , 315714980,  shawn.yakir@mail.huji.ac.il
- Sarah Levitz, 324673623, sarah.levitz@mail.huji.ac.il
- Carmel Baris, 318455276, carmel.baris@mail.huji.ac.il 

### Clean the environment
```{r clean}
rm(list = ls())
```

### Libraries used

```{r libraries}
library('splines')
```


### Paths
```{r paths}
path = "~/Carmel/RProjects/Lab_Benjamini/data"
# path = "/Users/alevi/Downloads/"
 # path = "\\Users\\shawn\\Desktop\\"
```


### Load data
```{r dat}
load(sprintf("%s/reads_100_A2.rda",path))
load(sprintf("%s/reads_100_B2.rda",path))
load(sprintf("%s/GC_100.rda",path))
```

### Binning
```{r binning}
binsize = 25

chr2t_mat = matrix(reads_100_A2, nr = binsize)
chr2n_mat = matrix(reads_100_B2, nr = binsize)
GC_100=GC_100[1: (length(reads_100_A2)) ]
gc_mat = matrix(GC_100,nr=binsize)

reads2.5K_t2 = colSums(chr2t_mat)
reads2.5K_n2 = colSums(chr2n_mat)
GC2.5K = colMeans(gc_mat)

length(reads2.5K_n2) == length(reads2.5K_t2)

## ------------------------------------------------
rm("chr2n_mat","chr2t_mat","gc_mat","reads_100_A2","reads_100_B2","GC_100") # remove from memory
```


### Colors setup


```{r colors}
color_tumor = rgb(0.8, 0.8, 0.8, 0.6)
col_healthy = rgb(0.3, 0.3, 0.3, 0.4)
```


### Functions

Fitting bspline regression:

```{r fit}
f = function(X, Y, deg=3, knots=c(0.415, 0.45, 0.54), subs) {
  lm(Y ~ bs(X, degree = deg, knots = knots, Boundary.knots = c(min(X), max(X))),
     subset = subs)
}

```

```{r even_knots}
 # Set the knots evenly within the range of x, ensuring no duplicates
  unique_x <- unique(train_data$x)
  if (length(unique_x) < num_knots + 2) {
    stop("Not enough unique x values to create the specified number of knots.")
  }
  knots <- quantile(unique_x, probs = seq(0, 1, length.out = num_knots + 2)[-c(1, num_knots + 2)], na.rm = TRUE)
  
```

```{r optimal_knots}
# Function to select the optimal number of knots
select_optimal_knots_cv <- function(x, y, min_knots, max_knots, k) {
  results <- data.frame(knots = integer(), mse = numeric())
  
  for (num_knots in min_knots:max_knots) {
    mse <- k_fold_cv(x, y, k, num_knots)
    results <- rbind(results, data.frame(knots = num_knots, mse = mse))
  }
  
  optimal_knots <- results$knots[which.min(results$mse)]
  optimal_mse <- min(results$mse)
  
  return(list(optimal_knots = optimal_knots, optimal_mse = optimal_mse, results = results))
}
```



### Healthy Fit vs. Tumor Fit
```{r fit_models}
l_2n = length(r_health_cln)
l_2t = length(r_tumor_cln)

myknots = c(0.415, 0.45, 0.54)
# Define the range for predictions
pred_range = seq(0.2,0.75,0.01)

GC=GC_cln[1:l_2n]
r_health_cln = r_health_cln
r_tumor_cln = r_tumor_cln

subs_n = (r_health_cln>50)&(r_health_cln<350)
subs_t = (r_tumor_cln>50)&(r_tumor_cln<350)

# mod_2n = f(GC, r_health_cln, subs = subs_n)
# mod_2t = f(GC, r_tumor_cln, subs = subs_n)
mod_2n = lm(r_health_cln~bs(GC, degree = 3),subset = subs_n)
mod_2t = lm(r_tumor_cln~bs(GC, degree = 3),subset = subs_t)

resp2n = predict(mod_2n,list(GC=pred_range))
preds_2n = predict(mod_2n,list(GC=GC_cln))

resp2t = predict(mod_2t,list(GC=pred_range))
preds_2t = predict(mod_2t,list(GC=GC_cln))

```

```{r fit_bs}
# Fit B-spline Regression Models
GC_healthy = GC2.5K
mod_healthy = lm(reads2.5K_n2 ~ bs(GC_healthy, degree = 3))

pred_healthy = predict(mod_healthy, list(GC_healthy = GC_healthy))
# Tumor Sample
reads2.5K_t2_cl = reads2.5K_t2[1:l_2n]  # Ensure tumor data matches in length
mod_tumor = lm(reads2.5K_t2 ~ bs(GC_healthy, degree = 3))
pred_tumor = predict(mod_tumor, list(GC_healthy = GC_healthy))

```

```{r pred_range}
# Predict values over the range for both models
preds_healthy = predict(mod_healthy, newdata = data.frame(GC_healthy = pred_range))
preds_tumor = predict(mod_tumor, newdata = data.frame(GC_healthy = pred_range))

```

```{r plot_Ys_GC}
# Combined Plot
par(mfcol = c(1, 1), mar = c(5, 5, 4, 2))

# Plot the data points first
plot(GC_healthy, reads2.5K_t2, col = col_healthy, pch = 20, cex = 0.5, ylab = "Binned Reads (2,500 per bin)", xlab = "GC Content", main = "Healthy vs Tumor Sample", ylim = c(0,400))
points(GC_healthy, reads2.5K_n2, col = color_tumor, pch = 20, cex = 0.5)

# Add the regression lines on top
lines(pred_range, preds_healthy, col = 'darkblue', lwd = 2)
lines(pred_range, preds_tumor, col = 'darkred', lwd = 2)

# Add legend
legend("topleft", legend = c("Tumor Sample", "Healthy Sample"), col = c(col_healthy, color_tumor), pch = 20, bty = "n")

```
