---
title: "Lab Task 8"
author: "Group 6"
date: "`r format(Sys.time(), '%d/%m/%y')`"
output:
  html_document:
    code_folding: show
editor_options: 
  markdown: 
    wrap: sentence
---

Group members:

- Shawn Yakir , 315714980,  shawn.yakir@mail.huji.ac.il
- Sarah Levitz, 324673623, sarah.levitz@mail.huji.ac.il
- Carmel Baris, 318455276, carmel.baris@mail.huji.ac.il 

### Clean the environment
```{r clean}
rm(list = ls())
```

### Colors

```{r colors}
color_tumor = rgb(0.8, 0.8, 0.8, 0.6)
col_healthy = rgb(0.3, 0.3, 0.3, 0.4)
```



### Libraries used

```{r libraries}
library('splines')
```


### Paths
```{r paths}
path = "C:/Users/user/Documents/Carmel/Projects/HUJI/Archive_HUJI/data-analysis-genomics/data"
# path = "/Users/alevi/Downloads/"
 # path = "\\Users\\shawn\\Desktop\\"
```


### Load data
```{r dat}
load(sprintf("%s/reads_100_A2.rda",path))
load(sprintf("%s/reads_100_B2.rda",path))
load(sprintf("%s/GC_100.rda",path))
```

### Binning
```{r binning}
binsize = 25

chr2t_mat = matrix(reads_100_A2, nr = binsize)
chr2n_mat = matrix(reads_100_B2, nr = binsize)
GC_100=GC_100[1: (length(reads_100_A2)) ]
gc_mat = matrix(GC_100,nr=binsize)

reads2.5K_t2 = colSums(chr2t_mat)
reads2.5K_n2 = colSums(chr2n_mat)
GC2.5K = colMeans(gc_mat)

length(reads2.5K_n2) == length(reads2.5K_t2)
```


```{r clean_env1}
rm("chr2n_mat","chr2t_mat","gc_mat","reads_100_A2","reads_100_B2","GC_100") # remove from memory
```


### Outliers
```{r outliers_new}
find_out_boxplot = function(dat) {
  out = boxplot.stats(dat)$out
  out_ind = dat %in% out
  return(as.integer(out_ind))
}

out_t2 = find_out_boxplot(reads2.5K_t2)
out_n2 = find_out_boxplot(reads2.5K_n2)
# out_reads_xtra = (reads2.5K_t2<5) | (reads2.5K_n2<5)

outliers = (out_t2 | out_n2)
r_health_cln = reads2.5K_n2[!outliers]
r_tumor_cln = reads2.5K_t2[!outliers]
GC_cln = GC2.5K[!outliers]

cat("removed", round((1-(length(GC_cln)/length(GC2.5K)))*100,2),"% outliers")
```


```{r clean_env2}
## ============================================================
rm("path", "find_out_boxplot","out_n2","out_reads_xtra","out_t2") # remove from memory
# rm("GC2.5K", "reads2.5K_n2", "reads2.5K_t2") # remove from memory
```


### Functions for GC Regression

Fitting bspline regression:

```{r even_knots}
# outputs evenly spaced knot vectors for different numbers of knots
create_knots <- function(x, min_knots = 1, max_knots = 10) {
  min_x <- min(x)
  max_x <- max(x)
  knots_list <- lapply(min_knots:max_knots, function(k) {
    seq(min_x, max_x, length.out = k + 2)[-c(1, k + 2)]
  })
  return(knots_list)
}

# Exclude 0 values from the GC range
GC_above0 <- GC_cln[GC_cln != 0]
r_health_above0 <- r_health_cln[GC_cln != 0]
r_tumor_above0 <- r_tumor_cln[GC_cln != 0]
knots_list_nonzero <- create_knots(GC_above0)

# Exclude GC values smaller than 0.3
GC_above.3 <- GC_cln[GC_cln >= 0.3]
r_health_above.3 <- r_health_cln[GC_cln >= 0.3]
r_tumor_above.3 <- r_tumor_cln[GC_cln >= 0.3]
knots_list_filtered <- create_knots(GC_above.3)

# Create knot vectors for original data
knots_list <- create_knots(GC_cln)

# Display knot vectors
# knots_list
# knots_list_nonzero
# knots_list_filtered
```

```{r new}

f = function(X_cln, Y_cln, deg = 3, knots) {
# f = function(X, Y, deg = 3, knots, subs) {
  # Ensure X and Y lengths match before fitting the model
  # X_cln = X[subs]
  # Y_cln = Y[subs]
  
  # Check for and remove NA or non-finite values
  # finite_indices = which(is.finite(X_cln) & is.finite(Y_cln))
  # X_cln = X_cln[finite_indices]
  # Y_cln = Y_cln[finite_indices]
  cat("Length of X_cln",length(X_cln),"\n")
  cat("Length of Y_cln",length(Y_cln),"\n")
  cat("Summary of X_cln","\n")
  print(summary(X_cln))
  cat("Summary of Y_cln","\n")
  print(summary(Y_cln))
  lm(Y_cln ~ splines::bs(X_cln, degree = deg, knots = knots, Boundary.knots = c(min(X_cln), max(X_cln))))
}

# Example usage with adjusted function f

# Ensure all necessary data is cleaned and matches in length
l_2n = length(r_health_cln)
pred_range = seq(0.2, 0.75, 0.01)
GC = GC_cln[1:l_2n]

# Define subsets for filtering
subs_n = (r_health_cln > 50) & (r_health_cln < 350)
subs_t = (r_tumor_cln > 50) & (r_tumor_cln < 350)

# Fit models using the updated function
mod_2n = f(GC_above0, r_health_above0, 3, knots_list[[1]])
# mod_2n = f(GC, r_health_cln, 3, knots_list[[1]], subs_n)
mod_2t = f(GC_above0, r_tumor_above0, 3, knots_list[[1]])
# mod_2t = f(GC, r_tumor_cln, 3, knots_list[[1]], subs_t)

# Make predictions
predict_data = data.frame(seq(0, length(GC_above0), 0.01))
predict_data$resp2n = predict(mod_2n, predict_data)
predict_data$resp2t = predict(mod_2n, predict_data)
preds2n = predict(mod_2n, list(GC_above0))
preds2t = predict(mod_2t, list(GC_above0))
resp2t = predict_data$resp2t
resp2n = predict_data$resp2n

#We'll use regular intervals so the line would come out nicely
plot(GC_cln,r_tumor_cln,ylim = c(0,500), cex = 0.3 )

# lines only works well if x variable is sorted. 
lines(predict_data$GC_5K, predict_data$yhat, col=4, lw = 3)


# Plotting function
# plot_fits = function(GC_above0, r_health_cln, r_tumor_cln, knots_list) {
plot_fits = function(GC, r_health_cln, r_tumor_cln, knots_list, pred_range) {
  par(mfrow = c(1, 2), mar = c(5, 4, 4, 2) + 0.1)
  
  # Plot for healthy sample
  plot(GC_above0, r_health_cln, main = "Healthy Sample", xlab = "GC", ylab = "Reads")
  for (knots in knots_list) {
    subs_n = (r_health_cln > 50) & (r_health_cln < 350)
    mod_2n = f(GC_above0, r_health_cln, 3, knots)
    resp2n = predict(mod_2n, list(GC_cln = pred_range))
    lines(pred_range, resp2n, col = "red")
  }
  
  # Plot for tumor sample
  plot(GC, r_tumor_cln, main = "Tumor Sample", xlab = "GC", ylab = "Reads")
  for (knots in knots_list) {
    subs_t = (r_tumor_cln > 50) & (r_tumor_cln < 350)
    mod_2t = f(GC_above0, r_tumor_cln, 3, knots)
    resp2t = predict(mod_2t, list(GC_cln = pred_range))
    lines(pred_range, resp2t, col = "blue")
  }
}

# Example call to plot fits
plot_fits(GC_above0, r_health_cln, r_tumor_cln, knots_list, pred_range)
# plot_fits(GC_above0, r_health_cln, r_tumor_cln, knots_list)


# Fit B-spline Regression Models
GC_healthy = GC2.5K
mod_healthy = lm(reads2.5K_n2 ~ bs(GC_healthy, degree = 3))

pred_healthy = predict(mod_healthy, list(GC_healthy = GC_healthy))
# Tumor Sample
reads2.5K_t2_cl = reads2.5K_t2[1:l_2n]  # Ensure tumor data matches in length
mod_tumor = lm(reads2.5K_t2 ~ bs(GC_healthy, degree = 3))
pred_tumor = predict(mod_tumor, list(GC_healthy = GC_healthy))
```


```{r old}
# Function to fit the model
f <- function(X, Y, deg = 3, knots, subs) {
  lm(Y[subs] ~ splines::bs(X[subs], degree = deg, knots = knots, Boundary.knots = c(min(X), max(X))))
}

# Loop over knot vectors and create plots
plot_fits <- function(GC, r_health_cln, r_tumor_cln, knots_list, pred_range) {
  l_2n <- length(r_health_cln)
  GC <- GC[1:l_2n]
  subs_n <- (r_health_cln > 50) & (r_health_cln < 350)
  subs_t <- (r_tumor_cln > 50) & (r_tumor_cln < 350)
  
# Set up the plotting area with adjusted margins
  par(mfrow = c(2, length(knots_list)), mar = c(4, 4, 2, 1))  
  for (knots_vec in knots_list) {
    # Fit models
    mod_2n <- f(GC, r_health_cln, 3, knots_vec, subs_n)
    mod_2t <- f(GC, r_tumor_cln, 3, knots_vec, subs_t)
    
    # Predictions
    resp2n <- predict(mod_2n, list(GC = pred_range))
    preds2n <- predict(mod_2n, list(GC = GC))
    resp2t <- predict(mod_2t, list(GC = pred_range))
    preds2t <- predict(mod_2t, list(GC = GC))
    
    # Plot for healthy samples
    plot(GC, r_health_cln, main = paste("Knots:", length(knots_vec), " - Healthy"), col = "blue", pch = 16)
    lines(pred_range, resp2n, col = "red")
    points(GC, preds2n, col = "green", pch = 16)
    
    # Plot for tumor samples
    plot(GC, r_tumor_cln, main = paste("Knots:", length(knots_vec), " - Tumor"), col = "blue", pch = 16)
    lines(pred_range, resp2t, col = "red")
    points(GC, preds2t, col = "green", pch = 16)
  }
}

# Example data
# GC_cln <- runif(100, 0, 1)
# r_health_cln <- rnorm(100, 200, 50)
# r_tumor_cln <- rnorm(100, 200, 50)

# Create knot vectors for original data
knots_list <- create_knots(GC_cln)

# Define prediction range
pred_range <- seq(0.2, 0.75, 0.01)

# Plot fits
plot_fits(GC_cln, r_health_cln, r_tumor_cln, knots_list, pred_range)

```


### Healthy Fit vs. Tumor Fit
```{r fit_models}

pred_range = seq(0.2,0.75,0.01)

myknots = c(0.415, 0.45, 0.54)

mod_2n = lm(r_health_cln~bs(GC_cln, degree = 3, knots = myknots))
preds2n = predict(mod_2n,list(GC_cln))
resp2n = predict(mod_2n,list(pred_range))

mod_2t = lm(r_tumor_cln~bs(GC_cln, degree = 3, knots = myknots))
resp2t = predict(mod_2t,list(pred_range))
preds2t = predict(mod_2t,list(GC_cln))


# l_2n = length(r_health_cln)
# subs_n = (r_health_cln>50)&(r_health_cln<350)
# subs_t = (r_tumor_cln>50)&(r_tumor_cln<350)

# GC=GC_cln
# mod_2n = f(GC, r_health_cln, subs = subs_n)
# mod_2t = f(GC, r_tumor_cln, subs = subs_n)
# mod_2n = lm(r_health_cln~bs(GC, degree = 3),subset = subs_n)
# mod_2t = lm(r_tumor_cln~bs(GC, degree = 3),subset = subs_t)


# resp2n = predict(mod_2n,list(GC=pred_range))
# preds2n = predict(mod_2n,list(GC=GC_cln))
# resp2t = predict(mod_2t,list(GC=pred_range))
# preds2t = predict(mod_2t,list(GC=GC_cln))

```

```{r fit_bs}
# Fit B-spline Regression Models
# GC_healthy = GC2.5K
# mod_healthy = lm(reads2.5K_n2 ~ bs(GC_healthy, degree = 3))
# mod_healthy = lm(r_health_cln ~ bs(GC_cln, degree = 3))

# pred_healthy = predict(mod_healthy, list(GC_healthy = GC_healthy))
# Tumor Sample
# reads2.5K_t2_cl = reads2.5K_t2[1:l_2n]  # Ensure tumor data matches in length
# mod_tumor = lm(reads2.5K_t2 ~ bs(GC_healthy, degree = 3))
# pred_tumor = predict(mod_tumor, list(GC_healthy = GC_healthy))

```

```{r preds}
# Define the range for predictions
# pred_range = seq(0.2, 0.75, 0.01)

# Predict values over the range for both models
# preds_healthy = predict(mod_healthy, newdata = data.frame(GC_healthy = pred_range))
# preds_tumor = predict(mod_tumor, newdata = data.frame(GC_healthy = pred_range))

```

```{r plot_Ys_GC2}
# Combined Plot
par(mfcol = c(1, 1), mar = c(5, 5, 4, 2))

# Plot the data points first
plot(GC_cln, r_health_cln, col = col_healthy, pch = 20, cex = 0.5, ylab = "Binned Reads (2,500 per bin)", xlab = "GC Content", main = "Healthy vs Tumor Sample", ylim = c(0,400))
points(GC_cln, r_tumor_cln, col = color_tumor, pch = 20, cex = 0.5)

# Add the regression lines on top
lines(pred_range, preds2n, col = 'darkblue', lwd = 2)
lines(pred_range, preds2t, col = 'darkred', lwd = 2)

# Add legend
legend("topleft", legend = c("Tumor Sample", "Healthy Sample"), col = c(col_healthy, color_tumor), pch = 20, bty = "n")
grid(nx = NULL, ny = NULL,
     lty = 2,      # Grid line type
     col = "gray", # Grid line color
     lwd = 2) 
```


```{r plot_Ys_GC}
# Combined Plot
par(mfcol = c(1, 1), mar = c(5, 5, 4, 2))

# Plot the data points first
plot(GC_healthy, reads2.5K_t2, col = col_healthy, pch = 20, cex = 0.5, ylab = "Binned Reads (2,500 per bin)", xlab = "GC Content", main = "Healthy vs Tumor Sample", ylim = c(0,400))
points(GC_healthy, reads2.5K_n2, col = color_tumor, pch = 20, cex = 0.5)

# Add the regression lines on top
lines(pred_range, preds_healthy, col = 'darkblue', lwd = 2)
lines(pred_range, preds_tumor, col = 'darkred', lwd = 2)

# Add legend
legend("topleft", legend = c("Tumor Sample", "Healthy Sample"), col = c(col_healthy, color_tumor), pch = 20, bty = "n")

```


